# Submit via `condor_submit /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/run_fine_tuning.sub`
# Monitor progress via `condor_q`

executable = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/run_LOOCV_fine_tuning.sh

# Docker image
container_image = docker://alyssaaanastasi/haven:v5

universe = container
initial_dir = /home/aranastasi/spillover
preserve_relative_paths = True

# Log paths
log = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.log
error = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.err
output = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.out

# Resources needed - use GPUs
+WantGPULab = true
+GPUJobLength = "long"

request_gpus = 1
gpus_minimum_capability = 7.0
gpus_minimum_memory = 20000
request_cpus = 1
request_memory = 32GB
request_disk = 64GB

# Input files
# Transfers entire repo, bad practice in CHTC
# transfer_input_files = /home/aranastasi/spillover/HAVEN
# Transfer files that are specifically used 
transfer_input_files = /home/aranastasi/spillover/HAVEN/input/config-files/virus_host_prediction/kuzmin/kuzmin-fine-tuning.yaml,
/home/aranastasi/spillover/HAVEN/input/data/kuzmin/kuzmin_no_gaps.csv,
/home/aranastasi/spillover/HAVEN/output/haven_pretrained_viral_seq.pth,
/home/aranastasi/spillover/HAVEN/src/pipelines/virus_host_prediction_training/TEST_kuzmin_fine_tuning_pipeline.py, 
/home/aranastasi/spillover/HAVEN/src/training_accessories/early_stopping.py,
/home/aranastasi/spillover/HAVEN/src/utils,
/home/aranastasi/spillover/HAVEN/src/run.py,
/home/aranastasi/spillover/HAVEN/src/models/baseline/nlp


requirements = (HasCHTCStaging == true)

# Run 5 replicates, using process number of 0...4 as replicate identifier 
queue 5
