# Submit via `condor_submit /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/run_fine_tuning.sub`
# Monitor progress via `condor_q`

executable = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/run_fine_tuning.sh
# arguments = $(Cluster) $(Process) $(dirname) $(species_to_withhold) $(model_type) $(cv_seed)

# Docker image
container_image = docker://alyssaaanastasi/haven:v0

# Apptainer image created from docker://ryanmoreno/mgm:v0
# container_image = file:///staging/aranastasi/mgm/mgm_apptainer.sif
universe = container
initial_dir = /home/aranastasi/spillover
preserve_relative_paths = True

# Log paths
log = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.log
error = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.err
output = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.out

# Resources needed
request_cpus = 4
For non-bagged models like the CNN or LSTM, 32GB mem and 64GB disk is plenty
request_memory = 32GB
request_disk = 64GB

# When training bagged models, more memory and disk are needed
# request_memory = 128GB
# request_disk = 128GB

# Input files
transfer_input_files = /home/aranastasi/spillover/HAVEN
requirements = (HasCHTCStaging == true)

# Run as many instances of the job as defined in params file
queue 1
