# Submit via `condor_submit /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/run_fine_tuning.sub`
# Monitor progress via `condor_q`

executable = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/run_fine_tuning.sh

# Docker image
container_image = docker://alyssaaanastasi/haven:v5

universe = container
initial_dir = /home/aranastasi/spillover
preserve_relative_paths = True

# Log paths
log = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.log
error = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.err
output = /home/aranastasi/spillover/HAVEN/chtc_use/HTCondor/logs/finetune_model_$(Cluster)_$(Process)_haven.out

# Resources needed - use GPUs
+WantGPULab = true
+GPUJobLength = "long"

request_gpus = 1
gpus_minimum_capability = 7.0
gpus_minimum_memory = 20000
request_cpus = 1
request_memory = 32GB
request_disk = 64GB

# Input files
transfer_input_files = /home/aranastasi/spillover/HAVEN
requirements = (HasCHTCStaging == true)

# Run once
queue 4
